### ISSUE TITLE
sonar-scanner throws parsing error for sonarqube-generic-coverage.xml

### ISSUE THREAD

**Issue by satyadev-chauhan** [SonarSource/sonar-scanning-examples#100]
**Error generic coverage report:**
INFO: ------------- Run sensors on project
INFO: Sensor Generic Coverage Report
INFO: Parsing /Users/<path>/sonarqube-generic-coverage.xml
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 2:58.549s
INFO: Final Memory: 63M/240M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarScanner execution
ERROR: Error during parsing of the generic coverage report '/Users/<path>/sonarqube-generic-coverage.xml'. Look at SonarQube documentation to know the expected XML format.

**Description:**
The sonar-scanner throws parsing error for sonarqube-generic-coverage.xml when file **size >2MB** generated by [xccov-to-sonarqube-generic.sh](https://github.com/SonarSource/sonar-scanning-examples/blob/master/swift-coverage/swift-coverage-example/xccov-to-sonarqube-generic.sh). The coverage reports are generated for **Generic Coverage** correctly as per https://docs.sonarqube.org/latest/analysis/generic-test/
<img width="1411" alt="Screenshot 2021-01-08 at 2 37 54 PM" src="https://user-images.githubusercontent.com/45193444/103996430-d6d7c380-51bf-11eb-9e70-13cb74a2539e.png">

The project uses swift and objective-c language. The reporting is successful when the sonarqube-generic-coverage.xml is around 2MB.
<img width="818" alt="Screenshot 2021-01-08 at 2 29 14 PM" src="https://user-images.githubusercontent.com/45193444/103996394-c9bad480-51bf-11eb-9b10-4a3dd6838e94.png">

**Info:**
SonarScanner 4.5.0.2216
Java version 8, 11, 15
Mac OS X 10.15.6 x86_64

**Comment by satyadev-chauhan** [comment]
Got this working with https://github.com/mysugr/cococo

**Instead of using this:**
bash xccov-to-sonarqube-generic.sh Build/Logs/Test/*.xcresult/ > sonarqube-generic-coverage.xml

**Use this:**
cococo Build/Logs/Test/*.xcresult > sonarqube-generic-coverage.xml

**Comment by niharamin86** [comment]
Running into the same but even cococo has been deprecated.  https://github.com/mysugr/cococo Does anyone have a solution ?

**Comment by okorach** [comment]
This repo is a sample of how to scan projects.
If you have problems on your own projects please post on the SonarSource community forum, not here. See https://community.sonarsource.com
