### ISSUE TITLE
xccov-to-sonarqube-generic.sh takes long time in Xcode12 

### ISSUE THREAD

**Issue by radhap** [SonarSource/sonar-scanning-examples#104]
We recently upgraded to Xcode 12 and noticed the below issue.

01:47:46  + ./xccov-to-sonarqube-generic.sh ./fastlane/ui_test_output/ABCEarlGreyTests.xcresult

01:47:46  2021-01-06 22:47:46.049 xccov[24889:354229] Requested but did not find extension point with identifier Xcode.IDEFoundation.IDEResultKitSerializationConverter
03:34:20  2021-01-07 00:34:20.420 xccov[40613:629084] Requested but did not find extension point with identifier Xcode.IDEFoundation.IDEResultKitSerializationConverter
03:34:20  [Pipeline] junit
03:34:20  Recording test results

Any suggestions? Thanks!

**Comment by niharamin86** [comment]
facing the same, is there a solution?

**Comment by okorach** [comment]
This repo is a sample of how to scan projects.
If you have problems on your own projects please post on the SonarSource community forum, not here. See https://community.sonarsource.com
