### ISSUE TITLE
Build-wrapper links to a page, which is not found

### ISSUE THREAD

**Issue by kohldampfer** [SonarSource/sonar-scanning-examples#11]
In the Readme in the directory _sonarqube-scanner-build-wrapper-linux_, the link to build-wrapper links to https://docs.sonarqube.org/pages/viewpage.action?pageId=7996665docs When visiting this link, I get a "Page not found"-message.

**Comment by dalinicus** [comment]
This link is still broken.  Looks like the "docs" at the end of the link isn't supposed to be there.  The following URL works.

https://docs.sonarqube.org/pages/viewpage.action?pageId=7996665

**Comment by okorach** [comment]
Opening an issue on that repo is not the right way to report issues on the documentation. Please go to https://community.sonarsource.com
