### ISSUE TITLE
wildcard support for jacocoxmlreports path is not working as expected

### ISSUE THREAD

**Issue by sai1408** [SonarSource/sonar-scanning-examples#124]
As per the documentation it says this property "sonar.coverage.jacoco.xmlReportPaths" supports wildcards 
https://docs.sonarqube.org/latest/analysis/coverage/

But if I try to use wildcard like below, it is not working and showing code coverage as '0'.

sonar.coverage.jacoco.xmlReportPaths=**/jacoco.xml
If I give absolute path to the jacoco.xml file then only it is working and showing code coverage.
Isn't it supposed to work with wildcards as the documentation says?

**Comment by jeff-zapotoczny-sonarsource** [comment]
This example repo is not the best place to seek help with problems. I suggest you instead post your question on our [Community Forum](https://community.sonarsource.com/).
