### ISSUE TITLE
fatal error compiling

### ISSUE THREAD

**Issue by ukreddy-erwin** [SonarSource/sonar-scanning-examples#130]
with java 1.8 and also tried with java 11 openjdk

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project
 sonarscanner-maven-basic: Fatal error compiling: invalid flag: --release -> [Help 1]

**Comment by sylvain-combe-sonarsource** [comment]
Hi  @ukreddy-erwin
you need to be much more specific with any such report.
