### ISSUE TITLE
xccov-to-sonarqube-generic.sh Fails on Xcode 13.2

### ISSUE THREAD

**Issue by AlbGarciam** [SonarSource/sonar-scanning-examples#132]
`xcrun --show-sdk-version` command executed on line 42 raises the following issue when executing it on Xcode version equal or greater than 13.2. The error it raises is:

```
xcodebuild: error: SDK "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk" cannot be located.
xcrun: error: unable to lookup item 'SDKVersion' in SDK '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk'
```

We have installed it from scratch Xcode and it starts failing from 13.2. The rest of the commands are working properly. Is it possible to disable the optimization instead of exiting the workflow?

Thanks

**Comment by waterskier2007** [comment]
We are seeing the same issue on Xcode 13.2.1

**Comment by waterskier2007** [comment]
We experienced this on our build machine. I attempted to reproduce locally, but the conversion & posting of results was successful. I did have to change the command line tools version in Xcode locally as it was not properly set. There was a mismatch of the command line tools on our build machine (relative to the version of Xcode used to perform our tests & generate the results file), so I have change that to match and I am going to see if that changes the result of the conversion on our build machine.

**Comment by AlbGarciam** [comment]
> We experienced this on our build machine. I attempted to reproduce locally, but the conversion & posting of results was successful. I did have to change the command line tools version in Xcode locally as it was not properly set. There was a mismatch of the command line tools on our build machine (relative to the version of Xcode used to perform our tests & generate the results file), so I have change that to match and I am going to see if that changes the result of the conversion on our build machine.

In our case it was happening in both. I don't know if it may be related but I downloaded the version from the developer portal and not from the AppStore

**Comment by waterskier2007** [comment]
Circling back, our issue seemed to be resolved when the version of the command line tools matches the version of Xcode that generated the test results.

**Comment by knox** [comment]
This becomes obsolete with #145

**Comment by joe-tingsanchali-sonarsource** [comment]
Please see our latest updates including updated references to the improved `xccov-to-sonarqube-generic.sh` script (in this repository) and the [Test coverage parameters](https://docs.sonarqube.org/latest/analyzing-source-code/test-coverage/test-coverage-parameters) documentation:

> ### Swift with Xcode 13.3+
> You can use the [xccov-to-sonarqube-generic.sh](https://github.com/SonarSource/sonar-scanning-examples/blob/master/swift-coverage/swift-coverage-example/xccov-to-sonarqube-generic.sh) script from the [sonar-scanning-examples/swift-coverage](https://github.com/SonarSource/sonar-scanning-examples/tree/master/swift-coverage) project to convert output from Xcode 13.3's xccov tool to the [Generic test data](https://docs.sonarqube.org/latest/analyzing-source-code/test-coverage/generic-test-data/) format.
>
> See the [community guide](https://community.sonarsource.com/t/coverage-test-data-generate-reports-for-swift/9700) for help with importing your coverage or test data.

If you continue to have issues, please respond here and we can take a look together. Or just report it at [Sonar Community](https://community.sonarsource.com/) for more eyes to look at it.
> ### Swift with Xcode 7-13.2
> #### sonar.swift.coverage.reportPaths
> Path to the report generated by llvm-cov show. The path may be absolute or relative to the project root.
