### ISSUE TITLE
Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar (default-cli) on project api: Unable to execute SonarQube: Fail to get bootstrap ind ex from server: Failed to connect to localhost/127.0.0.1:9000: SONAR COMMUNITY) 

### ISSUE THREAD

**Issue by jgsistem** [SonarSource/sonar-scanning-examples#136]
**SONAR RUN 1:**
mvn sonar:sonar \
  -Dsonar.projectKey=api-student \
  -Dsonar.host.url=http://localhost:9000 \
  -Dsonar.login=19ee31f62388dced29d8a4292b8d81fc131ba88a

**ERROR IN EXECUTION WITHIN DOCKER 1**
![ERROR](https://user-images.githubusercontent.com/6495393/153742380-76eeedb8-f424-4108-ae4b-01815f7ea845.JPG)
maven_1  | [INFO] --- sonar-maven-plugin:3.7.0.1746:sonar (default-cli) @ api ---
maven_1  | [INFO] User cache: /root/.sonar/cache
maven_1  | [ERROR] SonarQube server [http://localhost:9000] can not be reached
maven_1  | [INFO] ------------------------------------------------------------------------
maven_1  | [INFO] BUILD FAILURE
maven_1  | [INFO] ------------------------------------------------------------------------
maven_1  | [INFO] Total time:  1.016 s
maven_1  | [INFO] Finished at: 2022-02-13T06:41:56Z
maven_1  | [INFO] ------------------------------------------------------------------------
maven_1  | [ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar (default-cli) on project api: Unable to execute SonarQube: Fail to get bootstrap ind
ex from server: Failed to connect to localhost/127.0.0.1:9000: Connection refused (Connection refused) -> [Help 1]

**SONAR RUN 2:**
mvn clean verify sonar:sonar \
  -Dsonar.projectKey=api-student \
  -Dsonar.host.url=http://localhost:9000 \
  -Dsonar.login=19ee31f62388dced29d8a4292b8d81fc131ba88a

**ERROR IN EXECUTION WITHIN DOCKER 2**
![ERROR2](https://user-images.githubusercontent.com/6495393/153742524-f32fdf98-eed8-4fce-a614-d2b2ea0037ad.JPG)

maven_1  | [INFO] ------------------------------------------------------------------------
maven_1  | [ERROR] Failed to execute goal org.apache.maven.plugins:maven-clean-plugin:3.1.0:clean (default-clean) on project api: Failed to clean project: Failed to delete /tmp/target -> [Help
 1]
maven_1  | [ERROR] 
maven_1  | [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
maven_1  | [ERROR] Re-run Maven using the -X switch to enable full debug logging.
maven_1  | [ERROR]
maven_1  | [ERROR] For more information about the errors and possible solutions, please read the following articles:
maven_1  | [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**POM**:
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.1.3.RELEASE</version>
		<relativePath/> 
	</parent>

	<groupId>com.mitocode.sample</groupId>
	<artifactId>api</artifactId>
	<version>1.0.23</version>
	<name>api</name>
	<description>Demonstration project</description>

	<properties>
		<java.version>11</java.version>
		<frontend-maven-plugin.version>1.6</frontend-maven-plugin.version>
		<node.version>v10.13.0</node.version>
		<yarn.version>v1.12.1</yarn.version>
		<dependency.jacoco.version>0.8.6</dependency.jacoco.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-jdbc</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.flywaydb</groupId>
			<artifactId>flyway-core</artifactId>
		</dependency>
		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
		</dependency>
		<dependency>
			<groupId>org.postgresql</groupId>
			<artifactId>postgresql</artifactId>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.assertj</groupId>
			<artifactId>assertj-core</artifactId>
			<version>3.12.2</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.13.1</version>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.1</version>
			</plugin>
			
			<plugin>
				<groupId>org.jacoco</groupId>
				<artifactId>jacoco-maven-plugin</artifactId>
				<version>${dependency.jacoco.version}</version>
				<configuration>
					<excludes>
						
					</excludes>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>prepare-agent</goal>
						</goals>
					</execution>
					<execution>
						<id>report</id>
						<phase>prepare-package</phase>
						<goals>
							<goal>report</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			
			<plugin>
				<groupId>org.sonarsource.scanner.maven</groupId>
				<artifactId>sonar-maven-plugin</artifactId>
				<version>3.7.0.1746</version>
			</plugin>
		</plugins>
	</build>

	<profiles>
		<profile>
			<id>coverage</id>
			<activation>
				<activeByDefault>true</activeByDefault>
			</activation>
			<build>
				<plugins>
					<plugin>
						<groupId>org.jacoco</groupId>
						<artifactId>jacoco-maven-plugin</artifactId>
						<executions>
							<execution>
								<id>prepare-agent</id>
								<goals>
									<goal>prepare-agent</goal>
								</goals>
							</execution>
							<execution>
								<id>report</id>
								<goals>
									<goal>report</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
</project>

**Comment by sylvain-combe-sonarsource** [comment]
Hi @jgsistem 
This is obviously not related to this maven project analysis. You reach out though the SonarSource community.
And if your SonarQube instance listens on port 9000 of the docker network, that's port 9000 as well from your terminal only if you configured the right port mapping.
