### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by sitting-duck** [SonarSource/sonar-scanning-examples#139]
**OS**: Windows 11
**Browser**: Chrome Version 99.0.4844.82 (Official Build) (64-bit)  

![image](https://user-images.githubusercontent.com/1289702/159946433-a5080f0f-c053-4a91-add9-a56cacc894e4.png)

In screencap above I have highlighted in Green the broken link. 

**Page URL**: https://github.com/SonarSource/sonar-scanning-examples/tree/master/sonarqube-scanner-msbuild/CSharpProject

**Link Text**: SonarScanner for MSBuild

<img width="291" alt="image" src="https://user-images.githubusercontent.com/1289702/159946920-2a6f80e7-a5bf-42ce-87f4-79838e4f05a1.png">

Page screencap above is a visual on where I am taken after clicking that link. 
Thanks, please reach out if you need any more details to recreate this issue.

**Comment by sylvain-combe-sonarsource** [comment]
Thanks for spotting this broken link, fixed with #140
