### ISSUE TITLE
The process sonar-scanner failed with exit code null

### ISSUE THREAD

**Issue by liulangdexiaoxin** [SonarSource/sonar-scanning-examples#155]
![image](https://user-images.githubusercontent.com/52564449/223609296-2979f4b4-85f8-4b93-8fda-b2c60d1f00b7.png)
When i use sonar-scanner to analyzed my project, i meet such error.  I don't know why. Can someone help me to resolve such error or give me some suggestions? Thanks.

**Comment by joe-tingsanchali-sonarsource** [comment]
Hello @liulangdexiaoxin,

Please use https://community.sonarsource.com/ for getting further assistance. You will need to get DEBUG logs from your ADO build. Please add `sonar.verbose=true` to get DEBUG logs and attach your logs and your Azure pipeline yaml in a new thread on that Sonar community forum.
