### ISSUE TITLE
When I run the command, show the result is : Not authorized.

### ISSUE THREAD

**Issue by xuri422** [SonarSource/sonar-scanning-examples#156]
D:\sonar-scanning-examples-master\sonarqube-scanner-gradle\gradle-basic>gradlew.bat -D'sonar.host.url=http://XX.XX.XX.XX:9000' sonar
> Task :sonar FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sonar'.
> Not authorized. Analyzing this project requires authentication. Please provide a user token in sonar.token or other credentials in sonar.login and sonar.password.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
3 actionable tasks: 1 executed, 2 up-to-date

So, How can I authorized?
I have tried to input below in gradle.properties:
sonar.login=xxx
sonar.password=xxx
systemProp.sonar.host.url=http://10.1.7.142:9000

**Comment by joe-tingsanchali-sonarsource** [comment]
Hello @xuri422 ,

You should either use `sonar.token` (see https://docs.sonarqube.org/latest/user-guide/user-account/generating-and-using-tokens/) or ensure you have the proper permissions to analyze a project with your login and password.

For further help, please post your logs and what you have tried on [Sonar Community(https://community.sonarsource.com/), not on the issues page of the repository. You will get a better response time there.
