### ISSUE TITLE
sonar swift plugin issue

### ISSUE THREAD

**Issue by cah-iswaria-sasi** [SonarSource/sonar-scanning-examples#182]
is it only available to developer edition? xcode-to-generic.sh will be working for only developer edition or applicable to third party plugin too?

**Comment by joe-tingsanchali-sonarsource** [comment]
Hi @cah-iswaria-sasi , 

It depends. Swift language analysis is available with...
* SonarQube Developer Edition or higher.
* SonarCloud

**Comment by cah-iswaria-sasi** [comment]
Hi Joe,
do we have anything with community edition? just asking... if we opt for community edition, so whats the option to run our swift projects?

**Comment by joe-tingsanchali-sonarsource** [comment]
You need Developer Edition to scan Swift projects. See feature differences here: https://www.sonarsource.com/products/sonarqube/downloads/

For more assistance, I recommend you go to our Sonar Community forum: https://community.sonarsource.com/
