### ISSUE TITLE
Not authorized to run analysis Error

### ISSUE THREAD

**Issue by cunhaDev** [SonarSource/sonar-scanning-examples#185]
Guys, I'm using Sonar with Docker and when try the command `gradle clean build sonar -Dsonar.host.url=http://localhost:9001` I receiver this error:
![image](https://github.com/SonarSource/sonar-scanning-examples/assets/63728220/c3d6bab1-f815-47ed-9d19-8afee4138a35)

My setup:
Sonar from Docker:
![image](https://github.com/SonarSource/sonar-scanning-examples/assets/63728220/4bf55ee5-7e18-4806-a8e2-3ddbf796823d)

gradle.properties:
![image](https://github.com/SonarSource/sonar-scanning-examples/assets/63728220/b70e4126-8e42-4849-b7fe-1ac46933ad1a)

Thanks for help.

**Comment by sylvain-combe-sonarsource** [comment]
Hi @cunhaDev 
Please explore the [Sonar Community](https://community.sonarsource.com/) for existing resources regarding this problem, and raise a new topic there if you can't find a good one.
