### ISSUE TITLE
How to run java sonar-scanning-example

### ISSUE THREAD

**Issue by peterbollen** [SonarSource/sonar-scanning-examples#2]
Hi,

I noticed https://github.com/SonarSource/sonar-examples is DEPRECATED, and will be replaced by this repo and others.

How can I run these samples? For example the Java sample.

Thx,
Peter

**Comment by agigleux** [comment]
Hi Peter,

Please use the Community Channels to ask such question: https://www.sonarqube.org/community/feedback/

Thanks
