### ISSUE TITLE
analysis modes 

### ISSUE THREAD

**Issue by Hilalem** [SonarSource/sonar-scanning-examples#21]
commercial 7.0 version is used, what are current analysis modes? what are the differences between analysis.modes? What is the default analysis mode? which analysis modes  are deprecated, which are deleted
preview , issues, incremental, publish....
There is no clear documentation. We nee your help.

**Comment by okorach** [comment]
Hello @Hilalem , opening an issue is not the right way to get tech support on SonarQube and Scanners. Please go to https://community.sonarsource.com
