### ISSUE TITLE
Example of code coverage with generic coverage

### ISSUE THREAD

**Issue by cholloway13** [SonarSource/sonar-scanning-examples#33]
I'm looking for an example of a working python project with generic coverage data. It looks like https://github.com/SonarSource/sonar-scanning-examples/blob/master/sonarqube-scanner/sonar-project.properties is using the cobertura plugin. Is there an example of a project that uses generic coverage data somewhere?

**Comment by okorach** [comment]
Hello @cholloway13 this repo is only to show the basics of how to scan.
Using generic coverage data is already a more advanced used case. Out of scope of this simple repo.
Please go to https://community.sonarsource.com to get tech support on your request
