### ISSUE TITLE
SonarQube analyses C# issue Line 736 is out of range

### ISSUE THREAD

**Issue by quantumarun** [SonarSource/sonar-scanning-examples#36]
Hi Team,
I am facing below error while exeucting Sonar Analysis for C# project. Follow steps from:
https://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner+for+MSBuild

This is happening for both SonarCloud as well as Sonar Local instance.

Env Details:
SonarQube: 7.4
SonarScanner for MSBuild 4.4.2
SonarQube Scanner 3.2.0.1227
Java 1.8.0_131 Oracle Corporation (64-bit)
Mac OS X 10.13.6 x86_64

ERROR: Line 736 is out of range for file <Path>/xxxxx.cs. File has 735 lines.

Below is the short stacktrace.
INFO: Importing results from 6 proto files in ‘<Path>/.sonarqube/out/0/output-cs'
INFO: Importing results from 6 proto files in ‘<Path>/.sonarqube/out/1/output-cs'
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 4.903s
INFO: Final Memory: 23M/646M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarQube Scanner execution
**ERROR: Line 736 is out of range for file <Path>/xxxxx.cs. File has 735 lines.**
ERROR: 
The SonarQube Scanner did not complete successfully
10:03:23.755  Creating a summary markdown file...
10:03:23.763  Post-processing failed. Exit code: 1

More details are available also at:
https://stackoverflow.com/questions/53493806/sonarqube-analyses-issue-line-is-out-of-range-for

**Comment by quantumarun** [comment]
Can anyone help on this? I faced same issue with local setup as well.
Below are the version details:
SonarQube: 7.4.0.18908
SonarScanner: 3.3.0.1492
Downloaded SonarScanner for MSBuild 4.6.0.1930 from link https://docs.sonarqube.org/pages/viewpage.action?pageId=6954799

**Comment by okorach** [comment]
This repo is only to show the basics of how to scan.
Opening an issue on that repo is not the right way to get tech support. Please go to https://community.sonarsource.com
