### ISSUE TITLE
xccov-to-sonarqube-generic.sh   doesnt support code coverage for me

### ISSUE THREAD

**Issue by UMUTBAYGUT** [SonarSource/sonar-scanning-examples#37]
Hello , xccov-to-sonarqube-generic.sh  this code take a long time in my project.
My Xcode Version is 10 . So I don't have xccovarchive . I have xcresult file.
bash xccov-to-sonarqube-generic.sh Build/Logs/Tests/*xcresult/*_Test/action.xccovreport > sonar.xml

and this code take a about 5 hours. (xcresult file size 30 mb )

**Comment by UMUTBAYGUT** [comment]
I changed the action.xccovreport to action.xccovarchive/   . It is fast now. But I cant code coverage  in the sonar. İt shows 0 .

**Comment by dipikasrivastava16** [comment]
I have just now managed to get my stats up on the dashboard. I can try to help if you can post your logs.

**Comment by d4rkd3v1l** [comment]
@UMUTBAYGUT Are you sure the 2nd coverage generation worked? For me it was not working at first, as the path using Xcode 10 changed... Then I set it right, and got a 30MB file as well, after the script finished after about 9 hours.
Unfortunately the sonar-scanner cannot handle it -.-

> 09:27:48.225 ERROR: Error during SonarQube Scanner execution
> 09:27:48.225 ERROR: Error during parsing of the generic coverage report '/Users/martin.straub/Development/iphone-app/sonarqube-generic-coverage.xml'. Look at SonarQube documentation to know the expected XML format.
> 09:27:48.225 ERROR: Caused by: Unexpected '<'  in attribute value
>  at [row,col {unknown-source}]: [14,59]

Really annoying -.-

@dipikasrivastava16 Can you share you experience/fix? :-)

**Comment by guillermomartinez-accenture** [comment]
Hi,

My Sonar coverage report also shows 0.0%.
In the analysis report, I get `Unable to analyse file sonarqube-generic-coverage.xml;`

**Comment by narenjangir** [comment]
@UMUTBAYGUT @dipikasrivastava16 @d4rkd3v1l 

Guys, have you got the code coverage % on dashboard yet, I have tried multiple times and still shows 0.0%?

**Comment by dipikasrivastava16** [comment]
@UMUTBAYGUT Hey when I got my xml created, I got 0% because the path to the file was absolute and was wrong. So I modified the xccov-to-sonarqube-generic.sh to have the relative file path. This helped me in getting my percentage up on the dashboard

**Comment by narenjangir** [comment]
> @d4rkd3v1l @narenjangir Hey when I got my xml created, I got 0% because the path to each swift file inside the generated xml was absolute and was wrong. So I modified the xccov-to-sonarqube-generic.sh to have the relative file path. This helped me in getting my percentage up on the dashboard. I will suggest to check the generated XML and see if the path to each file inside XML is right.

Thanks @dipikasrivastava16  : could you please post your modified xccov-to-sonarqube-generic.sh here once?

**Comment by dipikasrivastava16** [comment]
```
function convert_file {
  local xccovarchive_file="$1"
  local file_name="$2"
  local relative="Source"
  local relativePath="${file_name#*$relative}"
  echo "  <file path=\"$relative$relativePath\">"
  xcrun xccov view --file "$file_name" "$xccovarchive_file" | \
    sed -n '
    s/^ *\([0-9][0-9]*\): 0.*$/    <lineToCover lineNumber="\1" covered="false"\/>/p;
    s/^ *\([0-9][0-9]*\): [1-9].*$/    <lineToCover lineNumber="\1" covered="true"\/>/p
    '
  echo '  </file>'
}
```

For my case, this script is running on a CI agent due to which paths were getting messed up.

**Comment by narenjangir** [comment]
> ```
> function convert_file {
>   local xccovarchive_file="$1"
>   local file_name="$2"
>   local relative="Source"
>   local relativePath="${file_name#*$relative}"
>   echo "  <file path=\"$relative$relativePath\">"
>   xcrun xccov view --file "$file_name" "$xccovarchive_file" | \
>     sed -n '
>     s/^ *\([0-9][0-9]*\): 0.*$/    <lineToCover lineNumber="\1" covered="false"\/>/p;
>     s/^ *\([0-9][0-9]*\): [1-9].*$/    <lineToCover lineNumber="\1" covered="true"\/>/p
>     '
>   echo '  </file>'
> }
> ```
> 
> For my case, this script is running on a CI agent using fastlane due to which paths were getting messed up.

so your "Source" is the absolute path of *.xccovarchive ?
mine also running in CI agent only

**Comment by dipikasrivastava16** [comment]
"Source" is the relative Path from .xcworkspace file, where all my source files sits like all my swift files which are scanned.. *.xccovarchive is in Derived Data.

**Comment by narenjangir** [comment]
> "Source" is the relative Path from .xcworkspace file, where all my source files sits like all my swift files which are scanned.. *.xccovarchive is in Derived Data.

@dipikasrivastava16 


xccovarchive PATH 
================
admins-Mac-Pro-2:action.xccovarchive jenkins$ pwd
/Users/jenkins/digitalbank-ios/ios/derivedData/Logs/Test/Test-DigitalBankTestsNew-2019.08.07_14-01-35-+0800.xcresult/1_Test/action.xccovarchive
admins-Mac-Pro-2:action.xccovarchive jenkins$ ls -lrt
total 304
rw-rr- 1 jenkins staff 236 Aug 7 14:08 Metadata.plist
rw-rr- 1 jenkins staff 77816 Aug 7 14:08 Coverage
rw-rr- 1 jenkins staff 70555 Aug 7 14:08 Index
admins-Mac-Pro-2:action.xccovarchive jenkins$
sonarqube-generic-coverage.xml generation using xccov-to-sonarqube-generic.sh 
===============================================================
sh /Applications/xccov-to-sonarqube-generic.sh ./derivedData/Logs/Test/.xcresult/_Test/*.xccovarchive > sonarqube-generic-coverage.xml
Scanning sonarqube-generic-coverage.xml 
==================================
sh /Applications/sonar-scanner/bin/sonar-scanner -Dsonar.projectKey=IOS_SONAR_TEST -Dsonar.sources=. -Dsonar.login=jenkins -Dsonar.password=Jenkins@May19 -Dsonar.swift.coverage.reportPath=sonarqube-generic-coverage.xml -Dsonar.cfamily.build-wrapper-output.bypass=true
Source of the project
==================
admins-Mac-Pro-2:ios jenkins$ pwd
/Users/jenkins/digitalbank-ios/ios
admins-Mac-Pro-2:ios jenkins$ ls -lrt
total 373920
drwxr-xr-x 4 jenkins staff 128 Jul 23 20:19 DigitalBank.xcworkspace
drwxr-xr-x 14 jenkins staff 448 Jul 23 20:20 DigitalBankTestsNew
drwxr-xr-x 4 jenkins staff 128 Jul 23 20:20 DigitalBankUITests
rw-rr- 1 jenkins staff 7669 Jul 23 20:20 UOB_Simple_TH_Store.mobileprovision
drwxr-xr-x 5 jenkins staff 160 Jul 23 20:20 mocks
-rwxr-xr-x 1 jenkins staff 3112 Jul 23 20:20 updatePODSDKs.sh
drwxr-xr-x 3 jenkins staff 96 Jul 23 20:49 appConstant
drwxr-xr-x 3 jenkins staff 96 Jul 23 20:58 build
rw-rr- 1 jenkins staff 454 Jul 23 21:37 exportOptions.plist
rw-rr- 1 jenkins staff 187193921 Jul 23 21:52 archive_name.ipa
drwxr-xr-x 4 jenkins staff 128 Aug 7 13:59 DigitalBank.xcodeproj
drwxr-xr-x 9 jenkins staff 288 Aug 7 13:59 DigitalBankTests
rw-rr- 1 jenkins staff 1703 Aug 7 13:59 Podfile
rw-rr- 1 jenkins staff 10725 Aug 7 13:59 Podfile.lock
rw-rr- 1 jenkins staff 13837 Aug 7 14:01 profile.mobileprovision
drwxr-xr-x 37 jenkins staff 1184 Aug 7 14:01 DigitalBank
drwxr-xr-x 38 jenkins staff 1216 Aug 7 14:07 Pods
drwxr-xr-x@ 8 jenkins staff 256 Aug 7 14:08 derivedData
rw-rr- 1 jenkins staff 0 Aug 7 14:34 test.xml
rw-rr- 1 jenkins staff 1498762 Aug 7 14:46 logfile.txt
rw-rr- 1 jenkins staff 1367500 Aug 7 14:53 sonarqube-generic-coverage.xml
OUTPUT of sonarqube-generic-coverage.xml
==================================
admins-Mac-Pro-2:ios jenkins$ more sonarqube-generic-coverage.xml
I am here
<coverage version="1">
<file path="/Users/jenkins/digitalbank-ios/ios/DigitalBank/AnticipateAndConverse/Features/Insights/Utils/InsightsHelper.swift">
<lineToCover lineNumber="12" covered="false"/>
<lineToCover lineNumber="13" covered="false"/>
<lineToCover lineNumber="14" covered="false"/>
<lineToCover lineNumber="15" covered="false"/>
<lineToCover lineNumber="19" covered="false"/>
<lineToCover lineNumber="20" covered="false"/>
<lineToCover lineNumber="21" covered="false"/>
<lineToCover lineNumber="22" covered="false"/>
<lineToCover lineNumber="23" covered="false"/>
<lineToCover lineNumber="24" covered="false"/>
<lineToCover lineNumber="25" covered="false"/>
<lineToCover lineNumber="26" covered="false"/>
<lineToCover lineNumber="30" covered="false"/>
<lineToCover lineNumber="31" covered="false"/>
<lineToCover lineNumber="32" covered="false"/>
<lineToCover lineNumber="33" covered="false"/>
<lineToCover lineNumber="37" covered="false"/>
<lineToCover lineNumber="38" covered="false"/>
<lineToCover lineNumber="39" covered="false"/>
<lineToCover lineNumber="40" covered="false"/>
<lineToCover lineNumber="44" covered="false"/>
<lineToCover lineNumber="45" covered="false"/>
<lineToCover lineNumber="46" covered="false"/>
<lineToCover lineNumber="47" covered="false"/>
<lineToCover lineNumber="51" covered="false"/>
<lineToCover lineNumber="52" covered="false"/>
<lineToCover lineNumber="53" covered="false"/>
<lineToCover lineNumber="54" covered="false"/>
<lineToCover lineNumber="55" covered="false"/>
<lineToCover lineNumber="56" covered="false"/>
<lineToCover lineNumber="60" covered="false"/>
<lineToCover lineNumber="61" covered="false"/>
<lineToCover lineNumber="62" covered="false"/>
<lineToCover lineNumber="63" covered="false"/>
<lineToCover lineNumber="67" covered="false"/>
<lineToCover lineNumber="68" covered="false"/>
<lineToCover lineNumber="69" covered="false"/>
<lineToCover lineNumber="70" covered="false"/>
<lineToCover lineNumber="74" covered="false"/>
<lineToCover lineNumber="75" covered="false"/>
<lineToCover lineNumber="76" covered="false"/>
<lineToCover lineNumber="77" covered="false"/>
<lineToCover lineNumber="78" covered="false"/>
<lineToCover lineNumber="82" covered="false"/>
<lineToCover lineNumber="83" covered="false"/>
<lineToCover lineNumber="84" covered="false"/>

**Comment by narenjangir** [comment]
> "Source" is the relative Path from .xcworkspace file, where all my source files sits like all my swift files which are scanned.. *.xccovarchive is in Derived Data.

@dipikasrivastava16 

xccovarchive PATH 
================
admins-Mac-Pro-2:action.xccovarchive jenkins$ pwd
/Users/jenkins/digitalbank-ios/ios/derivedData/Logs/Test/Test-DigitalBankTestsNew-2019.08.07_14-01-35-+0800.xcresult/1_Test/action.xccovarchive
admins-Mac-Pro-2:action.xccovarchive jenkins$ ls -lrt
total 304
rw-rr- 1 jenkins staff 236 Aug 7 14:08 Metadata.plist
rw-rr- 1 jenkins staff 77816 Aug 7 14:08 Coverage
rw-rr- 1 jenkins staff 70555 Aug 7 14:08 Index
admins-Mac-Pro-2:action.xccovarchive jenkins$
sonarqube-generic-coverage.xml generation using xccov-to-sonarqube-generic.sh 
===============================================================
sh /Applications/xccov-to-sonarqube-generic.sh ./derivedData/Logs/Test/.xcresult/_Test/*.xccovarchive > sonarqube-generic-coverage.xml
Scanning sonarqube-generic-coverage.xml 
==================================
sh /Applications/sonar-scanner/bin/sonar-scanner -Dsonar.projectKey=IOS_SONAR_TEST -Dsonar.sources=. -Dsonar.login=jenkins -Dsonar.password=Jenkins@May19 -Dsonar.swift.coverage.reportPath=sonarqube-generic-coverage.xml -Dsonar.cfamily.build-wrapper-output.bypass=true
Source of the project
==================
admins-Mac-Pro-2:ios jenkins$ pwd
/Users/jenkins/digitalbank-ios/ios
admins-Mac-Pro-2:ios jenkins$ ls -lrt
total 373920
drwxr-xr-x 4 jenkins staff 128 Jul 23 20:19 DigitalBank.xcworkspace
drwxr-xr-x 14 jenkins staff 448 Jul 23 20:20 DigitalBankTestsNew
drwxr-xr-x 4 jenkins staff 128 Jul 23 20:20 DigitalBankUITests
rw-rr- 1 jenkins staff 7669 Jul 23 20:20 UOB_Simple_TH_Store.mobileprovision
drwxr-xr-x 5 jenkins staff 160 Jul 23 20:20 mocks
-rwxr-xr-x 1 jenkins staff 3112 Jul 23 20:20 updatePODSDKs.sh
drwxr-xr-x 3 jenkins staff 96 Jul 23 20:49 appConstant
drwxr-xr-x 3 jenkins staff 96 Jul 23 20:58 build
rw-rr- 1 jenkins staff 454 Jul 23 21:37 exportOptions.plist
rw-rr- 1 jenkins staff 187193921 Jul 23 21:52 archive_name.ipa
drwxr-xr-x 4 jenkins staff 128 Aug 7 13:59 DigitalBank.xcodeproj
drwxr-xr-x 9 jenkins staff 288 Aug 7 13:59 DigitalBankTests
rw-rr- 1 jenkins staff 1703 Aug 7 13:59 Podfile
rw-rr- 1 jenkins staff 10725 Aug 7 13:59 Podfile.lock
rw-rr- 1 jenkins staff 13837 Aug 7 14:01 profile.mobileprovision
drwxr-xr-x 37 jenkins staff 1184 Aug 7 14:01 DigitalBank
drwxr-xr-x 38 jenkins staff 1216 Aug 7 14:07 Pods
drwxr-xr-x@ 8 jenkins staff 256 Aug 7 14:08 derivedData
rw-rr- 1 jenkins staff 0 Aug 7 14:34 test.xml
rw-rr- 1 jenkins staff 1498762 Aug 7 14:46 logfile.txt
rw-rr- 1 jenkins staff 1367500 Aug 7 14:53 sonarqube-generic-coverage.xml
OUTPUT of sonarqube-generic-coverage.xml
==================================
admins-Mac-Pro-2:ios jenkins$ more sonarqube-generic-coverage.xml
I am here
<coverage version="1">
<file path="/Users/jenkins/digitalbank-ios/ios/DigitalBank/AnticipateAndConverse/Features/Insights/Utils/InsightsHelper.swift">
<lineToCover lineNumber="12" covered="false"/>
<lineToCover lineNumber="13" covered="false"/>
<lineToCover lineNumber="14" covered="false"/>
<lineToCover lineNumber="15" covered="false"/>
<lineToCover lineNumber="19" covered="false"/>
<lineToCover lineNumber="20" covered="false"/>
<lineToCover lineNumber="21" covered="false"/>
<lineToCover lineNumber="22" covered="false"/>
<lineToCover lineNumber="23" covered="false"/>
<lineToCover lineNumber="24" covered="false"/>
<lineToCover lineNumber="25" covered="false"/>
<lineToCover lineNumber="26" covered="false"/>
<lineToCover lineNumber="30" covered="false"/>
<lineToCover lineNumber="31" covered="false"/>
<lineToCover lineNumber="32" covered="false"/>
<lineToCover lineNumber="33" covered="false"/>
<lineToCover lineNumber="37" covered="false"/>
<lineToCover lineNumber="38" covered="false"/>
<lineToCover lineNumber="39" covered="false"/>
<lineToCover lineNumber="40" covered="false"/>
<lineToCover lineNumber="44" covered="false"/>
<lineToCover lineNumber="45" covered="false"/>
<lineToCover lineNumber="46" covered="false"/>
<lineToCover lineNumber="47" covered="false"/>
<lineToCover lineNumber="51" covered="false"/>
<lineToCover lineNumber="52" covered="false"/>
<lineToCover lineNumber="53" covered="false"/>
<lineToCover lineNumber="54" covered="false"/>
<lineToCover lineNumber="55" covered="false"/>
<lineToCover lineNumber="56" covered="false"/>
<lineToCover lineNumber="60" covered="false"/>
<lineToCover lineNumber="61" covered="false"/>
<lineToCover lineNumber="62" covered="false"/>
<lineToCover lineNumber="63" covered="false"/>
<lineToCover lineNumber="67" covered="false"/>
<lineToCover lineNumber="68" covered="false"/>
<lineToCover lineNumber="69" covered="false"/>
<lineToCover lineNumber="70" covered="false"/>
<lineToCover lineNumber="74" covered="false"/>
<lineToCover lineNumber="75" covered="false"/>
<lineToCover lineNumber="76" covered="false"/>
<lineToCover lineNumber="77" covered="false"/>
<lineToCover lineNumber="78" covered="false"/>
<lineToCover lineNumber="82" covered="false"/>
<lineToCover lineNumber="83" covered="false"/>
<lineToCover lineNumber="84" covered="false"/>

**Comment by narenjangir** [comment]
@dipikasrivastava16 

I am able to generate sonar readable xml file using that xccov script and it only shows TRUE and FALSE after conversion NOT the percentage, is that why it is not publishing to Sonar Dashboard too ?

**Comment by narenjangir** [comment]
@dipikasrivastava16 

admins-Mac-Pro-2:ios jenkins$ more sonarqube-generic-coverage.xml
I am here
<coverage version="1">
<file path="/Users/jenkins/digitalbank-ios/ios/DigitalBank/AnticipateAndConverse/Features/Insights/Utils/InsightsHelper.swift">
<lineToCover lineNumber="12" covered="false"/>
<lineToCover lineNumber="13" covered="false"/>
<lineToCover lineNumber="14" covered="false"/>
<lineToCover lineNumber="15" covered="false"/>
<lineToCover lineNumber="19" covered="false"/>
<lineToCover lineNumber="20" covered="false"/>
<lineToCover lineNumber="21" covered="false"/>
<lineToCover lineNumber="22" covered="false"/>
<lineToCover lineNumber="23" covered="false"/>
<lineToCover lineNumber="24" covered="false"/>
<lineToCover lineNumber="25" covered="false"/>
<lineToCover lineNumber="26" covered="false"/>
<lineToCover lineNumber="30" covered="false"/>
<lineToCover lineNumber="31" covered="false"/>
<lineToCover lineNumber="32" covered="false"/>
<lineToCover lineNumber="33" covered="false"/>
<lineToCover lineNumber="37" covered="false"/>
<lineToCover lineNumber="38" covered="false"/>
<lineToCover lineNumber="39" covered="false"/>
<lineToCover lineNumber="40" covered="false"/>
<lineToCover lineNumber="44" covered="false"/>
<lineToCover lineNumber="45" covered="false"/>
<lineToCover lineNumber="46" covered="false"/>
<lineToCover lineNumber="47" covered="false"/>
<lineToCover lineNumber="51" covered="false"/>
<lineToCover lineNumber="52" covered="false"/>
<lineToCover lineNumber="53" covered="false"/>
<lineToCover lineNumber="54" covered="false"/>

**Comment by narenjangir** [comment]
@dipikasrivastava16 

admins-Mac-Pro-2:ios jenkins$ more sonarqube-generic-coverage.xml

<file path="/Users/jenkins/digitalbank-ios/ios/DigitalBank/AnticipateAndConverse/Features/Insights/Utils/InsightsHelper.swift">
<lineToCover lineNumber="12" covered="false"/>
<lineToCover lineNumber="13" covered="false"/>

**Comment by narenjangir** [comment]
[xccovarchive PATH.TXT](https://github.com/SonarSource/sonar-scanning-examples/files/3475765/xccovarchive.PATH.TXT)

**Comment by narenjangir** [comment]
@dipikasrivastava16 

Hi Dipika : Could I please connect you via phone? this is becoming a bottleneck in the project.

**Comment by dipikasrivastava16** [comment]
@narenjangir seeing your logs _sh /Applications/sonar-scanner/bin/sonar-scanner -Dsonar.projectKey=IOS_SONAR_TEST -Dsonar.sources=. -Dsonar.login=jenkins -Dsonar.password=Jenkins@May19 -Dsonar.swift.coverage.reportPath=sonarqube-generic-coverage.xml_ , it looks like the Dsonar.swift.coverage.reportPath is wrong as sonar-scanner will expect the xml in the same path as its own while your xml sits somewhere else.

**Comment by d4rkd3v1l** [comment]
Ok, finally I got it working, without actually modifying anything.. really strange.

Anyway, that's what I did:

Step 1:
```
xcodebuild -workspace myproject.xcworkspace -scheme myproject\ Debug -derivedDataPath Build/ -enableCodeCoverage YES clean build test -destination "name=iPhone Xs,OS=12.2"
```

Step 2:
```
bash xccov-to-sonarqube-generic.sh build/Logs/Test/*.xcresult/*_Test/*.xccovarchive/ > sonarqube-generic-coverage.xml
```

Step 3: (don't need any params, as they are already specified in my `sonar-project.properties` file)
```
sonar-scanner
```

my `sonar-project.properties` file:
```
# must be unique in a given SonarQube instance
sonar.projectKey=myproject-iOS

# Project description
sonar.projectDescription= myproject iOS App
 
# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
# This property is optional if sonar.modules is set. 
sonar.sources=myproject
sonar.tests=myprojectUnitTests,myprojectBehaviorTests,myprojectUITests
sonar.coverageReportPaths=sonarqube-generic-coverage.xml

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Ignore files
sonar.c.file.suffixes=-
sonar.cpp.file.suffixes=-
sonar.objc.file.suffixes=-

sonar.cfamily.build-wrapper-output.bypass=true
```

**Comment by gjudge** [comment]
I realize this thread is a bit old, but here is the problem and solution that worked for me.

Unless the file paths in the resultant sonarqube-generic-coverage.xml output are absolute and "real" (not referenced through some symbolic link), the SonarQube scanner is unable to find the reference source code.

A solution that worked for me was to modify the xccov-to-sonarqube-generic.sh as follows, to make sure the "real" full absolute path is used in the sonarqube-generic-coverage.xml output.

```
#!/usr/bin/env bash
set -euo pipefail

function convert_file {
  local xccovarchive_file="$1"
  local file_name="$2"
  local real_name=$(realpath $2)
  local xccov_options="$3"
  echo "  <file path=\"$real_name\">"
  xcrun xccov view $xccov_options --file "$file_name" "$xccovarchive_file" | \
    sed -n '
    s/^ *\([0-9][0-9]*\): 0.*$/    <lineToCover lineNumber="\1" covered="false"\/>/p;
    s/^ *\([0-9][0-9]*\): [1-9].*$/    <lineToCover lineNumber="\1" covered="true"\/>/p
    '
  echo '  </file>'
}

function xccov_to_generic {
  echo '<coverage version="1">'
  for xccovarchive_file in "$@"; do
    local xccov_options=""
    if [[ $xccovarchive_file == *".xcresult"* ]]; then
      xccov_options="--archive"
    fi
    xcrun xccov view $xccov_options --file-list "$xccovarchive_file" | while read -r file_name; do
      convert_file "$xccovarchive_file" "$file_name" "$xccov_options"
    done
  done
  echo '</coverage>'
}

xccov_to_generic "$@"
```

**Comment by bmwalters** [comment]
In my case I had to convert the paths in `sonarqube-generic-coverage.xml` from absolute to relative because the `xcresult` bundle was generated on a different machine with different paths. I achieved this by piping the output of `xccov-to-sonarqube-generic.sh` to `sed`:

```sh
SOURCES=MyLibrary
./xccov-to-sonarqube-generic.sh *.xcresult | sed "s/path=\".*$SOURCES/path=\"$SOURCES/" > sonarqube-generic-coverage.xml
```

**Comment by okorach** [comment]
Please follow-up on such problems on the SonarSource community (https://community.sonarsource.com), not on this sample repo.
Thanks
