### ISSUE TITLE
Imported coverage data for 0 files

### ISSUE THREAD

**Issue by dipikasrivastava16** [SonarSource/sonar-scanning-examples#40]
I get the below logs. I have checked that sonarqube-generic-coverage.xml is generated successfully. I am not sure why sonar is treating them as unknown files.

INFO: Source paths: IDKit/Source
 ▸ INFO: Source encoding: UTF-8, default locale: en_US
 ▸ INFO: Load server rules
▸ INFO: Load server rules (done) \| time=150ms
▸ WARN: Property 'sonar.abap.file.suffixes' is not declared as multi-values/property set but was read using 'getStringArray' method. The SonarQube plugin declaring this property should be updated.
▸ INFO: Language is forced to swift
▸ INFO: Index files
▸ WARN: File '/private/var/slaveadmin/bamboo-agent-home/xml-data/build-dir/dir/IDKit/Source/IDKit.h' is ignored because it doesn't belong to the forced language 'swift'
▸ INFO: 350 files indexed
▸ INFO: Quality profile for swift: Sonar way
▸ INFO: Sensor Generic Coverage Report
▸ INFO: Parsing /private/var/slaveadmin/bamboo-agent-home/xml-data/build-dir/dir/reports/sonar-generic-coverage.xml
▸ INFO: Imported coverage data for 0 files
▸ INFO: **Coverage data ignored for 290 unknown files**, including:
▸ /var/slaveadmin/bamboo-agent-home/xml-data/build-dir/dir/IDKit/Source/Analytics/Analytics.swift

Can you please suggest?

**Comment by dipikasrivastava16** [comment]
I found the issue. Somehow the path in the xml was different to actual path of the files which created the above error.

**Comment by junjia1983** [comment]
> I found the issue. Somehow the path in the xml was different to actual path of the files which created the above error.

Could you please share how you solve this issue? Thanks

**Comment by banshengbushu** [comment]
Basically, you need to confirm these two parts if you want to make the sonar unit test count show correctly.

1. Add config sonar.testExecutionReportPaths=xx/test-report.xml to properties and make sure the path is correct.
2. Check your `test-report.xml` file field and path content(`file path="C:\Program Files (x86)\Jenkins\workspace\CI\Tests\A-Test.cs"`), make sure the path is the same as the file in your local or server, for example, if you run this inside docker, you need to check the `A-Test.cs` file path in the docker container, whether it's the same with the defined path in xml file.

Finally, I solved my problem by doing this check, hopefully, it can help you.

In your case, better to check whether this file path is correct and really the same as the file path defined in your xml file `/var/slaveadmin/bamboo-agent-home/xml-data/build-dir/dir/IDKit/Source/Analytics/Analytics.swift`
