### ISSUE TITLE
Exclude androidTest and test folder

### ISSUE THREAD

**Issue by mukkumukesh** [SonarSource/sonar-scanning-examples#41]
How can exclude androidTest and Test folder from sonar analysis. I tried this but not working the report error.
`sonarqube {
    properties {
        property 'sonar.sources', "src/main/java"
        property 'sonar.exclusions', "/androidTest/**/*.java"
    }
    androidVariant 'devDebug'
}`

I am not write any test code that's why they return error when I am try to run `./gradlew sonarqube`.

Can you please suggest me how can I ignore these folder from sonar.

**Comment by ep4sh** [comment]
I had a similar issue, did you know about 

> sonar-project.properties

 file? 
I founded it with option:

>  sonar.exclusions=src/**
Works great

**Comment by wallacetju** [comment]
In my case, I used "sonar.exclusions=**/src/androidTest/**". It might not support pattern "/androidTest/**/*.java"

**Comment by okorach** [comment]
This repo is only to show the basics of how to scan.
Opening an issue on that repo is not the right way to get tech support. Please go to https://community.sonarsource.com
