### ISSUE TITLE
How to work without sonar-swift plugin?

### ISSUE THREAD

**Issue by ratanudit** [SonarSource/sonar-scanning-examples#47]
Hi @okorach,

Trying to implement the solution of xccov. In my company, I donot have admin rights to sonarqube so cannot download plugin. I need to generate code coverage for iOS somehow really soon.
Does using the "xccov-to-sonarqube-generic.sh" work to generate the coverage in jenkins?
P.S. : Also using XCTest for generating code coverage through command line.
I have to show the coverage in jenkins. 
Please help.

**Comment by okorach** [comment]
Opening an issue on that repo is not the right way to get tech support. Please go to https://community.sonarsource.com
