### ISSUE TITLE
Multi-module project example

### ISSUE THREAD

**Issue by skjolber** [SonarSource/sonar-scanning-examples#54]
I'm not able to configure the properties for a multi-module gradle project. Only works via command line so far. An example would be very helpful.

**Comment by bratwurzt** [comment]
I concur - the readme root pom (https://raw.githubusercontent.com/SonarSource/sonar-scanning-examples/master/sonarqube-scanner-maven/maven-multimodule/README.md) differs from actual pom (https://github.com/SonarSource/sonar-scanning-examples/blob/master/sonarqube-scanner-maven/maven-multimodule/pom.xml). Which one is right?

**Comment by fantianwen** [comment]
a gradle version can be helpful too

**Comment by joe-tingsanchali-sonarsource** [comment]
Thank you for your request.

We now have Gradle Multi-module project examples. Please check here: https://github.com/SonarSource/sonar-scanning-examples/tree/master/sonarqube-scanner-gradle
