### ISSUE TITLE
no line coverage with maven-multimodule example

### ISSUE THREAD

**Issue by jens-meiss** [SonarSource/sonar-scanning-examples#66]
Hi, 

i don't see any line coverage in Sonarqube UI if i run:

`mvn clean verify sonar:sonar`

on the project: 

* https://github.com/SonarSource/sonar-scanning-examples/tree/master/sonarqube-scanner-maven/maven-multimodule
* Sonarqube: Version 7.9.1 (build 27448)

I only see 6 Code Smells and the 4 Unit Tests.

I see the line coverage in the jacoco output in the project folder:

* sonarqube-scanner-maven/maven-multimodule/tests/target/site/jacoco-aggregate/index.html

Any hints what's maybe wrong?

**Comment by badgerwithagun** [comment]
Likewise.

**Comment by naresh-chaudhary** [comment]
@jens-meiss did you find a solve for this? I am also getting 0% line coverage in another project by following the exact same steps of multimodule project.

**Comment by joe-tingsanchali-sonarsource** [comment]
Hello,

For issues with using our example projects or any project, please create a new thread on our Sonar Community Forum: https://community.sonarsource.com/

Issues with regards to this specific repository belong here, but all other usage questions can be answered in the aforementioned forum.
