### ISSUE TITLE
invalid option '--archive'

### ISSUE THREAD

**Issue by cah-siddharth-paneri** [SonarSource/sonar-scanning-examples#67]
On the demo project itself, if I run
`bash xccov-to-sonarqube-generic.sh Build/Logs/Test/*.xcresult/*_Test/*.xccovarchive/ > sonarqube-generic-coverage.xml`
it gives me an error
`Error: Error Domain=DVTCommandLineParserErrorDomain Code=3 "invalid option '--archive'" UserInfo={NSLocalizedDescription=invalid option '--archive'}`
I am using **Xcode 10.2.1**

**Comment by alexpr** [comment]
+1

**Comment by davidahouse** [comment]
Ran into the same problem. The issue is with this change: https://github.com/SonarSource/sonar-scanning-examples/pull/64/files#diff-604570268bb6730c069ccec69eb2843bR21

That returns true for Xcode 10 test results, but `xccov` for Xcode 10 doesn't support `--archive`.

**Comment by rrolland** [comment]
+1

**Comment by iamhaseebiqbal** [comment]
+1

**Comment by joe-tingsanchali-sonarsource** [comment]
Please see our latest updates including updated references to the improved `xccov-to-sonarqube-generic.sh` script (in this repository) and the [Test coverage parameters](https://docs.sonarqube.org/latest/analyzing-source-code/test-coverage/test-coverage-parameters) documentation:

> ### Swift with Xcode 13.3+
> You can use the [xccov-to-sonarqube-generic.sh](https://github.com/SonarSource/sonar-scanning-examples/blob/master/swift-coverage/swift-coverage-example/xccov-to-sonarqube-generic.sh) script from the [sonar-scanning-examples/swift-coverage](https://github.com/SonarSource/sonar-scanning-examples/tree/master/swift-coverage) project to convert output from Xcode 13.3's xccov tool to the [Generic test data](https://docs.sonarqube.org/latest/analyzing-source-code/test-coverage/generic-test-data/) format.
>
> See the [community guide](https://community.sonarsource.com/t/coverage-test-data-generate-reports-for-swift/9700) for help with importing your coverage or test data.
> ### Swift with Xcode 7-13.2
> #### sonar.swift.coverage.reportPaths
> Path to the report generated by llvm-cov show. The path may be absolute or relative to the project root.

If you continue to have issues, please respond here and we can take a look together. Or just report it at [Sonar Community](https://community.sonarsource.com/) for more eyes to look at it.
