### ISSUE TITLE
 Requested but did not find extension point with identifier Xcode.IDEFoundation.IDEResultKitSerializationConverter

### ISSUE THREAD

**Issue by rkhandelwal17** [SonarSource/sonar-scanning-examples#69]
Hi Team,

Even after using the latest script (as mentioned) for xcode 11. I am getting the below error while running the coverage report script. am i missing anything here

These are the steps i followed to upgrade to xcode 11.3
1. Upgrade the OS to Catalina
2. Install Xcode 11.3 on the local machine
3. Install command line tools for Xcode 11.3

xccov[6953:154596] Requested but did not find extension point with identifier Xcode.IDEFoundation.IDEResultKitSerializationConverter

**Comment by HDZed** [comment]
Hi Team, the same for me.
Azure DevOps CI  failing with same result:

xccov[719:5743] Requested but did not find extension point with identifier Xcode.IDEFoundation.IDEResultKitSerializationConverter

Steps to reproduce:
 - import repo to a new project. 
 - create YAML azure-pipelines.yml and use default settings and steps from readme
 - Run Pipeline

[azure-pipelines.txt](https://github.com/SonarSource/sonar-scanning-examples/files/4036782/azure-pipelines.txt)

**Comment by andrewclaus** [comment]
I am seeing this same issue, but the sonarqube-generic-coverage.xml file is still getting generated, though I have not yet looked deep enough to see if it is missing coverage data.

Is this a warning that can be ignored? or it is going to be missing coverage data?

**Comment by HDZed** [comment]
I've made it to work with solution from akoller-vs 
https://github.com/SonarSource/sonar-scanning-examples/issues/68#issuecomment-571177428

**Comment by CarlosDParada** [comment]
Try with this https://github.com/mysugr/cococo/tree/v0.2.0

**Comment by joe-tingsanchali-sonarsource** [comment]
Please see our latest updates including updated references to the improved `xccov-to-sonarqube-generic.sh` script (in this repository) and the [Test coverage parameters](https://docs.sonarqube.org/latest/analyzing-source-code/test-coverage/test-coverage-parameters) documentation:

> ### Swift with Xcode 13.3+
> You can use the [xccov-to-sonarqube-generic.sh](https://github.com/SonarSource/sonar-scanning-examples/blob/master/swift-coverage/swift-coverage-example/xccov-to-sonarqube-generic.sh) script from the [sonar-scanning-examples/swift-coverage](https://github.com/SonarSource/sonar-scanning-examples/tree/master/swift-coverage) project to convert output from Xcode 13.3's xccov tool to the [Generic test data](https://docs.sonarqube.org/latest/analyzing-source-code/test-coverage/generic-test-data/) format.
>
> See the [community guide](https://community.sonarsource.com/t/coverage-test-data-generate-reports-for-swift/9700) for help with importing your coverage or test data.
> ### Swift with Xcode 7-13.2
> #### sonar.swift.coverage.reportPaths
> Path to the report generated by llvm-cov show. The path may be absolute or relative to the project root.

If you continue to have issues, please respond here and we can take a look together. Or just report it at [Sonar Community](https://community.sonarsource.com/) for more eyes to look at it.

**Comment by MikePendo** [comment]
I have the same issue using the script as suggested the xcresult was done with Xcode 14.3.1 on M1.
was it tested?
