### ISSUE TITLE
xccov-to-sonarqube-generic.sh is too slow on large projects

### ISSUE THREAD

**Issue by inforeqd512** [SonarSource/sonar-scanning-examples#72]
Hi 

Wondering if anyone has had similar problems when using this script on large projects. 
The script takes around 10+ minutes to run. 
Is there a work around or faster ruby script or fastlane plugin that we can use?

**Comment by nfgrilo** [comment]
You may want to take a look at the approach on the comment below. 

In our particular case, on CI, it dropped from ~10min needed to convert code coverage to sonar file format, to ~2min:
https://github.com/SonarSource/sonar-scanning-examples/issues/68#issuecomment-571177428

**Comment by okorach** [comment]
This repo is a sample of how to scan projects.
If you have problems on your own projects please post on the SonarSource community forum, not here. See https://community.sonarsource.com
