### ISSUE TITLE
Does not allow space in xcodeproj file name even with back-slash

### ISSUE THREAD

**Issue by kapadiamoheet** [SonarSource/sonar-scanning-examples#74]
I have a project name with space in it eg. 'some name.xcodeproj' also in .plist file. Therefore it fails to build the project. I had tried using 'some\ name.xcodeproj' for values in 'sonar.swift.project' and 'sonar.swift.workspace' properties but they do not work.

Any help is much. appreciated.

**Comment by sylvain-combe-sonarsource** [comment]
> I have a project name with space in it eg. 'some name.xcodeproj' also in .plist file. Therefore it fails to build the project. I had tried using 'some\ name.xcodeproj' for values in 'sonar.swift.project' and 'sonar.swift.workspace' properties but they do not work.
> 
> Any help is much. appreciated.

Hi @kapadiamoheet , may I suggest you to reach out to the SonarSource community to get some help or report an issue that is not directly related to this sonar-scanning-example repository? You'll find it at https://community.sonarsource.com

Best regards
Sylvain
