### ISSUE TITLE
How to set a specific jdk version to run sonar-runner?

### ISSUE THREAD

**Issue by suoha666** [SonarSource/sonar-scanning-examples#78]
How to set a specific jdk version to run sonar-runner?
I have tried all the sonar-scanner versions that they all deponds on the jdk1.8+.
But my server's jdk-version is below jdk1.8, how can I solve the problem?

**Comment by sylvain-combe-sonarsource** [comment]
Hello @suoha666 
There is no possibility for any earlier jdk version to be used. Java 8 was released in 2014 and is deprecated for all sonar scanners already, java 11 is the recommended version now.

You should solve your problem by using a supported jdk with all your builds, and get rid of the numerous critical security holes not patched in those old versions.

**Comment by suoha666** [comment]
> Hello @suoha666
> There is no possibility for any earlier jdk version to be used. Java 8 was released in 2014 and is deprecated for all sonar scanners already, java 11 is the recommended version now.
> 
> You should solve your problem by using a supported jdk with all your builds, and get rid of the numerous critical security holes not patched in those old versions.

I can install different jdk version in one server,such jdk1.7、jdk1.8、jdk9、jdk……
The default jdk version of the server is jdk1.6.
In this way，how can I run (sonar-runner)sonar-scanner in jdk1.8 or jdk9 enviroment.
for example:
We can run java on the same sever which has installed different jdk version:
/usr/local/src/java/jdk1.8.0_101/bin/java -jar demo1.jar
/usr/local/src/java/jdk1.7.0_101/bin/java -jar demo2.jar
/usr/local/src/java/jdk1.6.0_101/bin/java -jar demo2.jar

Is there some way to run sonar-scanner like above?

**Comment by sylvain-combe-sonarsource** [comment]
Hello @suoha666 
your question is not related to sonar-scanner then, but to how default java is set on your system (with JAVA_HOME basically).
Please use [SonarSource Community forum](https://community.sonarsource.com/) for questions on SonarSource products.

BR, Sylvain
