### ISSUE TITLE
Examples showing defaults per project that can be overridden?

### ISSUE THREAD

**Issue by basickarl** [SonarSource/sonar-scanning-examples#79]
Hi I'm trying to locate an example where the project has a default sonar properties file which can be added to source control and then another sonar properties file that a developer can then override the default settings.

Is this possible with sonarqube?

**Comment by sylvain-combe-sonarsource** [comment]
Hello @basickarl 
Feel free to use the [community support](https://community.sonarsource.com/), which is very active, for questions not directly related to this project.

Thank you and best regards
Sylvain
