### ISSUE TITLE
How to configure addtional arguments ?

### ISSUE THREAD

**Issue by oceanho** [SonarSource/sonar-scanning-examples#8]
Hi. @agigleux 
How can set the property `sonar.sourceEncoding` , I'm use `/d:sonar.sourceEncoding=utf-8` ,It's does not work .
can you give some idea ? 
thanks .

**Comment by Karunakar438** [comment]
[php_code.txt](https://github.com/SonarSource/sonar-scanning-examples/files/1068468/php_code.txt)

**Comment by agigleux** [comment]
Hello,

Please use the Community Channels to ask such question: https://www.sonarqube.org/community/feedback/

Thanks
