### ISSUE TITLE
The sonar-maven-plugin  does't support parallel compilation

### ISSUE THREAD

**Issue by yichuanjia** [SonarSource/sonar-scanning-examples#86]
as below,The sonar-maven-plugin 3.7  support parallel compilation.would you pls help to resolve it?
 
18:02:12 [INFO] --------------------------------[ pom ]---------------------------------
18:02:12 [WARNING] *****************************************************************
18:02:12 [WARNING] * Your build is requesting parallel execution, but project      *
18:02:12 [WARNING] * contains the following plugin(s) that have goals not marked   *
18:02:12 [WARNING] * as @threadSafe to support parallel building.                  *
18:02:12 [WARNING] * While this /may/ work fine, please look for plugin updates    *
18:02:12 [WARNING] * and/or request plugins be made thread-safe.                   *
18:02:12 [WARNING] * If reporting an issue, report it against the plugin in        *
18:02:12 [WARNING] * question, not against maven-core                              *
18:02:12 [WARNING] *****************************************************************
18:02:12 [WARNING] The following plugins are not marked @threadSafe in ad-project:
18:02:12 [WARNING] org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746
18:02:12 [WARNING] Enable debug to see more precisely which goals are not marked @threadSafe.
18:02:12 [WARNING] *****************************************************************
1

**Comment by okorach** [comment]
This repo is a sample of how to scan basic projects.
If you have problems on your own projects please post on the SonarSource community forum, not here. See https://community.sonarsource.com
