### ISSUE TITLE
The sample project should show the usage of: id "org.sonarqube" version "3.0"

### ISSUE THREAD

**Issue by octopus-prime** [SonarSource/sonar-scanning-examples#89]
The sample project shows the usage of id "org.sonarqube" version "2.7"
The sample project should show the usage of: id "org.sonarqube" version "3.0"

**Comment by sylvain-combe-sonarsource** [comment]
Thanks @octopus-prime 
indeed gradle sample project should be aligned with the documentation and thus use version 3.0.
