### ISSUE TITLE
If and will sonar-scanner-api(not msbuild scanner) be compatible with CSharp

### ISSUE THREAD

**Issue by wusisu** [SonarSource/sonar-scanning-examples#9]
I am developing something with [sonnar-scanner-api](https://github.com/SonarSource/sonar-scanner-api), and I face problem when I need to analyse csharp projects.
The only thing appears on sonarqube 5.6 is LoC (lines of code), and It fails on sonarqube 6.2.

I wonder if the only way to run csharp-project analysis is using [SonarQube Scanner for MSBuild](https://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner+for+MSBuild).

**Comment by cemp2703** [comment]
Not, you can analyse with sonan-scanner but says its is DEPRECATED

**Comment by wusisu** [comment]
Thanks for helping. 
I am going to try this later.
