### ISSUE TITLE
coverage lost after upgrading from version 2.8 to 3.0

### ISSUE THREAD

**Issue by octopus-prime** [SonarSource/sonar-scanning-examples#93]
This commit 
https://github.com/SonarSource/sonar-scanning-examples/pull/90/commits/b93205fd97fd27614b5f3ac75b6809f02d789947
shows that upgrading to version 3.0 is just changing the number.

So i did. But after upgrading the coverage drops from 100% to 0%.
See https://github.com/octopus-prime/zero/commit/601f0f86aa01c0a5e2b7ba3c3dc43aac1fc0647a
and https://sonarcloud.io/dashboard?id=octopus-prime_zero

What did i miss??

**Comment by sylvain-combe-sonarsource** [comment]
Hello @octopus-prime 
if you don't have a SonarSource support subscription, the best way to get help with any SonarSource Code Quality and Security tool(SonarCloud, SonarQube and the scanners) is with [SonarSource community forum](https://community.sonarsource.com/).
This said I can give you a hint here with the [gradle scanner 3.0 release notes](https://jira.sonarsource.com/secure/ReleaseNote.jspa?projectId=10974&version=15726).

Have a good day!
Sylvain

**Comment by octopus-prime** [comment]
Thanks @sylvain-combe-sonarsource for your hint.
`Remove the implicit dependency between 'sonarqube' task and 'test'`
That information i was looking for - works like a charm now :-)
