### ISSUE TITLE
Sonar report post 400 error

### ISSUE THREAD

**Issue by mail2ganeshcse** [SonarSource/sonar-scanning-examples#97]
Please help for the below error.. since i am running the sonar-scanner command directly on jenkins machine it works and genrates sonar reports to sonar dashboard, but its not happening in jenkins pipelin.. it throw below error...

0:56:07.723 DEBUG: Upload report
20:56:07.782 DEBUG: POST 400 http://xx.xx.xx.xx:9000/api/ce/submit?projectKey=stage-project-admin-Dsonar.projectName%3DGD-admin-Dsonar.language%3Dts-Dsonar.sources%3D%2Fhome%2Fjenkins%2Fworkspace%2Fstage-branch-admin%2Fdist%2Fproject-admin%2F-Dsonar.tests%3D%2Fhome%2Fjenkins%2Fworkspace%2Fstage-branch-admin%2Fdist%2Fproject-admin%2F | time=58ms
20:56:07.790 DEBUG: eslint-bridge server will shutdown
20:56:07.958 DEBUG: stylelint-bridge server will shutdown
20:56:07.961 INFO: ------------------------------------------------------------------------
20:56:07.961 INFO: EXECUTION FAILURE
20:56:07.961 INFO: ------------------------------------------------------------------------
20:56:07.961 INFO: Total time: 1:22.233s
20:56:08.103 INFO: Final Memory: 33M/1424M

**Comment by okorach** [comment]
This repo is a sample of how to scan projects.
If you have problems on your own projects please post on the SonarSource community forum, not here. See https://community.sonarsource.com
